window.BOOK_DATA = {
  site: {
    saga: "El ciclo inmóvil",
    book: "Los hijos del muro",
    author: "Escandar Giadach",
    part: "Libro I — Partes I a IV",
    description: "Audiolibro y archivo visual interactivo del universo de El ciclo inmóvil.",
    cover: "assets/cover/portada.webp",
    audioBaseUrl: "https://el-ciclo-inmovil.netlify.app/audio/",
    enableSpoilerMode: true
  },
  chapters: [
    { number: 1, title: "La vida que le quedaba", part: "Parte I — La vida que le quedaba", file: "parte-1/01-la-vida-que-le-quedaba.mp3" },
    { number: 2, title: "La segunda muerte", part: "Parte I — La vida que le quedaba", file: "parte-1/02-la-segunda-muerte.mp3" },
    { number: 3, title: "La historia correcta", part: "Parte I — La vida que le quedaba", file: "parte-1/03-la-historia-correcta.mp3" },
    { number: 4, title: "La línea blanca", part: "Parte I — La vida que le quedaba", file: "parte-1/04-la-linea-blanca.mp3" },
    { number: 5, title: "La marca roja", part: "Parte I — La vida que le quedaba", file: "parte-1/05-la-marca-roja.mp3" },
    { number: 6, title: "Los nombres prestados", part: "Parte I — La vida que le quedaba", file: "parte-1/06-los-nombres-prestados.mp3" },
    { number: 7, title: "Los nombres heredados", part: "Parte I — La vida que le quedaba", file: "parte-1/07-los-nombres-heredados.mp3" },
    { number: 8, title: "Lo que despierta", part: "Parte I — La vida que le quedaba", file: "parte-1/08-lo-que-despierta.mp3" },
    { number: 9, title: "La versión segura", part: "Parte II — Activación", file: "parte-2/09-la-version-segura.mp3" },
    { number: 10, title: "Lo que el frío obedece", part: "Parte II — Activación", file: "parte-2/10-lo-que-el-frio-obedece.mp3" },
    { number: 11, title: "El punto de apagado", part: "Parte II — Activación", file: "parte-2/11-el-punto-de-apagado.mp3" },
    { number: 12, title: "La fase pendiente", part: "Parte II — Activación", file: "parte-2/12-la-fase-pendiente.mp3" },
    { number: 13, title: "Lo que se hereda", part: "Parte II — Activación", file: "parte-2/13-lo-que-se-hereda.mp3" },
    { number: 14, title: "Lo que el tiempo entrena", part: "Parte II — Activación", file: "parte-2/14-lo-que-el-tiempo-entrena.mp3" },
    { number: 15, title: "La forma de una victoria", part: "Parte II — Activación", file: "parte-2/15-la-forma-de-una-victoria.mp3" },
    { number: 16, title: "Lo que no vuelve", part: "Parte II — Activación", file: "parte-2/16-lo-que-no-vuelve.mp3" },
    { number: 17, title: "El fuego que parece mío", part: "Parte III — Evolución", file: "parte-3/17-el-fuego-que-parece-mio.mp3" },
    { number: 18, title: "Las cosas que hacíamos por miedo", part: "Parte III — Evolución", file: "parte-3/18-las-cosas-que-haciamos-por-miedo.mp3" },
    { number: 19, title: "Una ventana en Última Sombra", part: "Parte III — Evolución", file: "parte-3/19-una-ventana-en-ultima-sombra.mp3" },
    { number: 20, title: "El costo de demostrarlo", part: "Parte III — Evolución", file: "parte-3/20-el-costo-de-demostrarlo.mp3" },
    { number: 21, title: "La versión suficiente", part: "Parte III — Evolución", file: "parte-3/21-la-version-suficiente.mp3" },
    { number: 22, title: "Gael Altaren", part: "Parte III — Evolución", file: "parte-3/22-gael-altaren.mp3" },
    { number: 23, title: "El derecho a decidir", part: "Parte III — Evolución", file: "parte-3/23-el-derecho-a-decidir.mp3" },
    { number: 24, title: "Los instrumentos", part: "Parte III — Evolución", file: "parte-3/24-los-instrumentos.mp3" },
    { number: 25, title: "La ruta prevista", part: "Parte IV — La Lanza de Vhal", file: "parte-3/25-la-ruta-prevista.mp3" },
    { number: 26, title: "Lo que dejaron abierto", part: "Parte IV — La Lanza de Vhal", file: "parte-3/26-lo-que-dejaron-abierto.mp3" },
    { number: 27, title: "La Lanza de Vhal", part: "Parte IV — La Lanza de Vhal", file: "parte-3/27-la-lanza-de-vhal.mp3" },
    { number: 28, title: "Pérdidas aceptables", part: "Parte IV — La Lanza de Vhal", file: "parte-3/28-perdidas-aceptables.mp3" },
    { number: 29, title: "La forma de salvarlo", part: "Parte IV — La Lanza de Vhal", file: "parte-3/29-la-forma-de-salvarlo.mp3" },
    { number: 30, title: "Todo lo que vuelve", part: "Parte IV — La Lanza de Vhal", file: "parte-3/30-todo-lo-que-vuelve.mp3" },
    { number: 31, title: "La puerta que queda abierta", part: "Parte IV — La Lanza de Vhal", file: "parte-3/31-la-puerta-que-queda-abierta.mp3" },
    { number: 32, title: "Los hijos del muro", part: "Parte IV — La Lanza de Vhal", file: "parte-3/32-los-hijos-del-muro.mp3" }
  ],
  library: [
    { id: "mundo-orbita", title: "El mundo", category: "Lugares", image: "assets/world/mundo-realista-final-2048.webp", unlockChapter: 1, caption: "Mapa realista canónico: Gran Noche, Nidum, Assum y Día Extremo conectados por un océano global activo." },
    { id: "atlas", title: "Atlas político", category: "Infografías", image: "assets/world/atlas-politico-final-2048.webp", unlockChapter: 1, caption: "Atlas político plano de las ciudades, Casas de Custodia y puntos estratégicos." },
    { id: "muro-vista", title: "Vista del muro", category: "Lugares", image: "assets/gallery/muro-vista.webp", unlockChapter: 1, caption: "El muro visto desde el exterior." },
    { id: "muro-interior", title: "Interior del muro", category: "Lugares", image: "assets/gallery/muro-interior.webp", unlockChapter: 2, caption: "El gran atrio de Nidum, en el interior del muro." },
    { id: "nidum", title: "Nidum", category: "Lugares", image: "assets/gallery/nidum.svg", unlockChapter: 1, caption: "Espacio para una vista o infografía de Nidum." },
    { id: "ian", title: "Ian de Vries", category: "Personajes", image: "assets/gallery/ian.webp", unlockChapter: 1, caption: "Ficha visual de Ian de Vries." },
    { id: "elian", title: "Elian Nahl", category: "Personajes", image: "assets/gallery/elian.webp", unlockChapter: 2, caption: "Elian Nahl durante la Parte I, antes de los cambios asociados a la Trascendencia." },
    { id: "vhal", title: "Vhal", category: "Lugares", image: "assets/gallery/vhal.webp", unlockChapter: 2, caption: "Vhal antes de su destrucción." },
    { id: "daren", title: "Daren de Vries", category: "Personajes", image: "assets/gallery/daren.webp", unlockChapter: 3, caption: "Daren de Vries a los catorce años." },
    { id: "kier", title: "Kier de Vries", category: "Personajes", image: "assets/gallery/kier.webp", unlockChapter: 3, caption: "Kier de Vries a los catorce años." },
    { id: "vigilia", title: "La Vigilia", category: "Emblemas", image: "assets/gallery/vigilia.webp", fit: "contain", unlockChapter: 4, caption: "Emblema oficial de La Vigilia." },
    { id: "lina", title: "Lina Aurelian", category: "Personajes", image: "assets/gallery/lina.webp", unlockChapter: 5, caption: "Lina Aurelian antes de la activación." },
    { id: "aurelian", title: "Emblema Aurelian", category: "Emblemas", image: "assets/gallery/aurelian.webp", fit: "contain", unlockChapter: 5, caption: "Emblema oficial de la Casa Aurelian." },
    { id: "sevrin", title: "Emblema Sevrin", category: "Emblemas", image: "assets/gallery/sevrin.webp", fit: "contain", unlockChapter: 7, caption: "Emblema oficial de la Casa Sevrin." },
    { id: "casas", title: "Casas de Custodia", category: "Infografías", image: "assets/gallery/casas-v2.webp", fit: "contain", unlockChapter: 7, caption: "Atlas de las catorce Casas de Custodia." },
    { id: "activacion", title: "La Activación", category: "Infografías", image: "assets/gallery/activacion.webp", fit: "contain", unlockChapter: 8, caption: "Reescritura fisiológica de la Corriente durante la Activación." }
  ]
};
